### PR TITLE
Make this package installable and provide example usage

### PR DESCRIPTION
**Pull request by doctorpangloss**

### CODE REVIEW

**Comment by chujiezheng** [comment]
Hi, thanks for your great work! Sorry that I do not have previous experience of making installable packages. May I ask what are the advantages of making this repo installable? Personally, I think it is convenient to (a) clone this repo and regularly pull the latest changes and then (b) use absolute/relative paths to load chat templates.

**Comment by doctorpangloss** [comment]
- you can include data files via dependencies from other packages. this is super handy for distributing files that my or other's code needs to function properly. it isn't easy to do with a git repo, or with a pile of files on a file system.
- making a package installable lets you easily share it with others. they can just pip install it without messing around with copying files manually.
- you can manage different versions of your package. this helps others to use a specific version they know works for them.
- having a setup.py or pyproject.toml file makes your project look serious and well-organized.
- by packaging your code, you help ensure that it runs in a consistent environment. this reduces the "works on my machine" problems when others use your package.
- once your package is installable, pushing updates is straightforward. users can upgrade with a simple pip command.
- installable packages work better with other tools and platforms, like continuous integration systems, which can automatically install and test your package.

**Comment by chujiezheng** [comment]
Thanks for sharing these valuable insights!

1. Since I am less experienced, would you like to be added as a `contributor` to this repo?
2. I noticed that you added LLaVA's chat template. This is a great point since the current repo only supports text-only models. One minor point is that currently, the template file names are concise and do not contain model size info (because different-sized models in the same model family usually adopt the same chat template). Since I am not very familiar with VLMs, do you agree that we can rename `llava-v1.6-mistral-7b-hf.jinja` to sth like `llava-mistral.jinja`?
3. If we make this repo installable, I suggest that we add a mapping object so that the users can directly map the HF model names (which can also be supplemented manually) to the corresponding chat template. If so, users will not need to pay attention to how we name the template files. For example:
```python
{
    "Mistral-7B-Instruct-v0.1": "mistral-v0.1",
    "Mistral-7B-Instruct-v0.3": "mistral",
    "openchat-3.5-0106": "openchat",
    "llava-v1.6-mistral-7b-hf": "llava-mistral",
}
```
(I realize that `openchat-3.6-xxx` has used the LLaMA-3 base model, so the current `openchat.jinja` is not applicable to it)

**Comment by doctorpangloss** [comment]
> Since I am less experienced, would you like to be added as a contributor to this repo?

Yes, I really appreciate the hard work you have put in to organize this stuff. You correctly found a pain point. I want a more robust approach to this since it's such a common problem with using other people's instruct models.

> I noticed that you added LLaVA's chat template. This is a great point since the current repo only supports text-only models. One minor point is that currently, the template file names are concise and do not contain model size info (because different-sized models in the same model family usually adopt the same chat template). Since I am not very familiar with VLMs, do you agree that we can rename llava-v1.6-mistral-7b-hf.jinja to sth like llava-mistral.jinja?

There is a lot of toil involved in using the content of this repo. If I were you, I would just duplicate the files and make the names line up. You are overestimating how much people can comprehend. They also will differ between model sizes eventually.

> If we make this repo installable, I suggest that we add a mapping object so that the users can directly map the HF model names (which can also be supplemented manually) to the corresponding chat template. If so, users will not need to pay attention to how we name the template files. For example:

Sounds good.

**Comment by chujiezheng** [comment]
Hi, I plan first to merge this PR and then add the mapping at a later time.

**Pull request merged**
